# ONLY FOR DEVELOPMENT
version: "3.9"
services:
  backend:
    image: ${SPORTSMAP_BACKEND_IMAGE}
    ports:
      - "8080:8080"
    environment:
      - API_DB_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - API_SUPERUSER_EMAIL="dev@example.com"
      - API_SUPERUSER_PASSWORD="qwerty"
      - AWS_URL="http://s3:9000"
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SSL=true
      - S3_BUCKET_NAME="sportsmap.spb.ru"
    depends_on:
      - db
      - s3
    restart: always
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  s3:
    container_name: s3
    image: docker.io/minio/minio
    command: server /data
    volumes:
      - s3_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
      - MINIO_ADDRESS=0.0.0.0:9000
      - MINIO_CONSOLE_ADDRESS=0.0.0.0:9001
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    restart: always

volumes:
  db_data:
  s3_data:
